name: Player Service Docker Image CI

on:
  push:
    branches: [ main ]
    paths-ignore: 
      -  "lts/**"
      -  "cts/**"
  pull_request:
    branches: [ main ]
    paths-ignore: 
      -  "lts/**"
      -  "cts/**"
## ignore the other projects in the group repo



jobs:

      
  Static-Scanning:
    environment: pipeline-environment
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_KEY }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        #projectBaseDir: /player
        args: >
          -Dsonar.projectKey=ellr-infrastructure
          -Dsonar.verbose=true
